language: perl
sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'

notificaitions:
  email: false
  slack:
    secure: iQ35AlCd2UUYi09ZMOlc2Em8YiFfktH1jdebucIa8y0jm+yoBkcftnePxnFBTjKXHzciu2RzOR1bUgnTcOzmzaEffx+mIH9f9ZaEyhSMb8giy9iWYzIZKKVeicpGDv3gYJm942ZOIsAMahqlE13SGG7AFeSJp9hUPsaU5Q66UjiHo0/WVyBGTXiVd68CyfI8UmEo9JcqtcmzrgHdwVnXarUSqQFiS3YcKcti89XvRNyJGq2HvhzACXCectDA9yU2C5szrXSIci4RuARYXt2jvjiKasACiiDphp+ucQNv0M6tR5tmNjgX1PakVJ+1FczhnuNhcnHygkTpAEo2Qe04aHGJWUyYLsNoEUA/nW91420tAs/Ek83ZJeFs45dRTsNwPKZf32hW/Q82qPu8N/MQF6luS2HyY8yJehLrnbQG3gQfKu4n6xWKlPaiVLAMk+z0/0jKoJC6ZOsbLTMfXMYR56R2akfgISwPVLL4eqy9IvAdrUlJxcLUjMpm9iq6ab5MVLCU0vxGCdoxmcTmkdYC8oZxY1oqx7+Zse7RILjvgptQzT5HhxwDZHO4x656BIUm2Yz1Axb+PyX3/CHmAeIQTXiPtBFJUNjZ/hnYRgNXhB0kUxGnZ3ivm4rK2af8H11IOQ39S6yX1Hjx41JZWz3MLDgQeBJMmN3zx+Rl73YxmLc=
