language: perl
sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'

notificaitions:
  email: false
  slack:
    secure: UUADbWywkBpndSLDE5nygZshIMIjPqsdGn3MA1euPxrJmnuPAosdcKS/S5knu/eP+pfJ0H7Wk5vNvgVpt3yLnhW9XftUBgGWVjp86fopBznQAIn1t1Sl8RCeMCrsvi0rBlUneyuHyP36WuxY75Y5LlZ02uuxCrPMTN1cC4+dehax0FahMWWDurV3flQwCw3X/1DKBpHTFuoD3Rqjc2MuMv9WPuOZvQIfXj1s5T2rJIHSubmbV4HZx8leHFIl4jZ8+/K97sa0yN1La8a+2zErgjW+Ge3MnxSxNm+ua6mEdmo8f38BNh+WdyFxx5cyBILcWx7tt9oWvzyNV8r13iVoNbMyeczuW8liM9RuYM+ATENADA3UnmGelxDwXEfn3NkIXWl0sX9XGJUdr0DKuDk256DdVqQ9TnIhZ2wU3hKBWJV7A9S4EqOGWVOLibCyaysKBrI46Q2vmyRMHUSdk8UBsbJEMIoBeLS3qDezODUwCveMrMF7amh9a0fM955nTo+bLjpeuoQeV3C80OexAcVG2+aaG8XMuLbRdw7CKpN9ocZdyk99tSL/zVZtcgYhc2JptsM2ogcY092d9rzZeR24GA3B3Y96wbv7zzams17K/xju6cbEp/TN7KaMN4FZn8y4pOs/Sp+RgGPon6G844LnXflNFOrvHWw7SWaz+Mgrj0o=
