language: perl
sudo: false
perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
notificaitions:
  email: false
  slack:
    secure: pqwG7Fos+3ig3EKzC4eh++WSt5TKxiLJlwcputh75893DZMM8qKqhKzzwW+1BrFiI8ajHVTKXvDXmPl5T5kukiHvvSVb57ogRUI2zxY3SpHdL3N+LAD7mgNhtrHEuEi3P6pgQsyEPhdQj+75TwXutBA5PsB/t/kPyRym4Dr5aKk5RrNHlecXibksTwEUFp7AFPA5Y/Lpc0ARIttXZd4I5M2eR1OEF0Cm0Sk5K/NMv2kEmCh1cgb8RLr7df+9aJBgfPiwhhge1ByiX8VxdL3nxPX3QF//yZP7+0C9Pk0VlTGfBxTWgPim2j3HD5EDJJEPuPo8zdsnPW+5kPcUFeTsVaahbh3gaQA5BC/d4LTxfpOiMSomciWzSvF8WFq4Zoj4yk4wQM+a6mmmqxe/ZbdPgKYNTkkeh4gFI4wBFhhSJ2NpXsTwkxc4XZzaLR6XsJ22O/8XAQDsQkAcCHBttx8snyqmOkZn7LuEml6RjCAeia9ZxIhGPxP2v29G0ylmE0I9eU7OXnTu8DtHCEljnlTXgD3FIlf/4K9xxEcQBASbp3zX5qtQBogU7KnGCbP+1UdkyTmZLKrBe+9Ff1bvLpfDiL34R3tQNZviHJudNjef3rfahoevOhNS6IK0agAmutRnxd7A10aUJ8/wTDKCM/+Rmu4Wihv4c3Es2Z0iD5E3hwo=
